# Generated by Django 5.0.2 on 2026-02-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField()),
                ('acepto_terminos', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
            },
        ),
    ]
